### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by kousikking** [harshilpatel1799/Iot-Cyber-Security-with-Machine-Learning#4]
Hi i am trying to download the usnw-nb15 dataset but unable to do it.If you have the dataset please send it to kousikchinna3@gmail.com

**Comment by harshilpatel1799** [comment]
Find them here: [https://cloudstor.aarnet.edu.au/plus/index.php/s/2DhnLGDdEECo4ys?path=%2F](url)
